services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: build
    environment:
      - ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=dice_game_db
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ../:/workspace/:cached
    command: ["your_production_start_command"]      

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dice_game_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: