services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: devcontainer
    # Despite being the default CMD it still needs to be specified...
    command: sleep infinity